"""empty message

Revision ID: bd598624f3fc
Revises: d866cce225c7
Create Date: 2020-08-16 23:55:11.340901

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "bd598624f3fc"
down_revision = "d866cce225c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "actors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("age", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "movies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("release_date", sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("movies")
    op.drop_table("actors")
    # ### end Alembic commands ###
