"""empty message

Revision ID: d866cce225c7
Revises: 61c2e828f841
Create Date: 2020-08-16 20:40:53.755978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd866cce225c7'
down_revision = '61c2e828f841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('actors', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
