"""empty message

Revision ID: e974427b23e9
Revises: bc583cd7ed22
Create Date: 2020-08-16 20:26:28.137547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e974427b23e9'
down_revision = 'bc583cd7ed22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
                    existing_type=sa.VARCHAR(length=80),
                    nullable=True)
    # ### end Alembic commands ###
